# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbLevel = QtWidgets.QProgressBar(self.centralwidget)
        self.pbLevel.setMaximum(1000)
        self.pbLevel.setProperty("value", 123)
        self.pbLevel.setTextVisible(False)
        self.pbLevel.setOrientation(QtCore.Qt.Vertical)
        self.pbLevel.setObjectName("pbLevel")
        self.horizontalLayout.addWidget(self.pbLevel)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.grFFT = PlotWidget(self.frame)
        self.grFFT.setObjectName("grFFT")
        self.verticalLayout.addWidget(self.grFFT)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.grPCM = PlotWidget(self.frame)
        self.grPCM.setObjectName("grPCM")
        self.verticalLayout_2.addWidget(self.grPCM)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 140))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 140))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_cal = QtWidgets.QWidget()
        self.tab_cal.setObjectName("tab_cal")
        self.btnReset = QtWidgets.QPushButton(self.tab_cal)
        self.btnReset.setGeometry(QtCore.QRect(220, 10, 114, 41))
        self.btnReset.setObjectName("btnReset")
        self.layoutWidget = QtWidgets.QWidget(self.tab_cal)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 139, 80))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnAmbient = QtWidgets.QPushButton(self.layoutWidget)
        self.btnAmbient.setCheckable(True)
        self.btnAmbient.setObjectName("btnAmbient")
        self.verticalLayout_5.addWidget(self.btnAmbient)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lcdSamples = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdSamples.setStyleSheet("color:rgb(0, 0, 206)")
        self.lcdSamples.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdSamples.setObjectName("lcdSamples")
        self.horizontalLayout_4.addWidget(self.lcdSamples)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_cal, "")
        self.tab_pars = QtWidgets.QWidget()
        self.tab_pars.setObjectName("tab_pars")
        self.tabWidget.addTab(self.tab_pars, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Passive Doppler Speed Sensor</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-style:italic; color:#3c26ce;\">Ian Gillingham @ 2019</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Frequency data (FFT):"))
        self.label_2.setText(_translate("MainWindow", "Raw data (PCM):"))
        self.btnReset.setText(_translate("MainWindow", "Reset"))
        self.btnAmbient.setToolTip(_translate("MainWindow", "Sample audio for background profile"))
        self.btnAmbient.setWhatsThis(_translate("MainWindow", "Ambient profile"))
        self.btnAmbient.setText(_translate("MainWindow", "Background\n"
"Listen"))
        self.label_5.setText(_translate("MainWindow", "Samples"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cal), _translate("MainWindow", "Calibrate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pars), _translate("MainWindow", "Parameters"))

from pyqtgraph import PlotWidget
